apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-volume
  labels:
    type: local
spec:
  storageClassName: gp2
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/d/data"
