apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocs-version-yml # tên của deployment
spec:
  replicas: 2 #số lượng bản sao
  selector:
    matchLabels:
      app: ocs-version-yml #chọn các pod có label = ocs-version-yml
  template:
    metadata:
      labels:
        app: ocs-version-yml #label của pods chứa container
    spec:
      containers:
        - name: ocs-app
          image: docker30041999/ocs-preparation:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: debug-port
              containerPort: 5005
              protocol: TCP
          env:
            - name: DATABASE #setting từ config map
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbName
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: port
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: user
            - name: PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: password
            - name: JAVA_TOOL_OPTIONS
              value: '-Xdebug -agentlib:jdwp=transport=dt_socket,address=0.0.0.0:5005,server=y,suspend=n'
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ocs-version-yml
spec:
  selector:
    app: ocs-version-yml #chọn các pod để expose dựa theo label của nó
  ports:
    - port: 8080 #port service lắng nghe request
      targetPort: 8080 #port service chuyển request đến
  type: LoadBalancer
