apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-db
  name: mongo-db
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "123456"
          image: mongo
          imagePullPolicy: Always
          name: mongo-db
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-persistent-storage
      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-db
  name: mongo-db
spec:
  ports:
    - name: mongodb
      nodePort: 30332
      port: 27017
  selector:
    app: mongo-db
  type: NodePort
